baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "JD's blog"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/hugo-sid"

[[params.socialIcons]]
name = "x"
url = "https://x.com"

[params]
  goToTop = true